---
language: node_js
node_js:
 - "10"
 - "8"

script: echo "Running tests against $(node -v) ..."


stages:
  - test

jobs:
  include:
    - stage: "test"
      env: NODE_ENV=test
      script: "npm run test"
