---
language: node_js

stages:
  - test

jobs:
  include:
    - stage: "test"
      node_js:
        - "10"
        - "8"
      env: NODE_ENV=test
      script: "npm run test"
      after_success:
        - "npm run reportCoverage"
